// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: homeControl.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "homeControl.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace homeControl {

namespace {

const ::google::protobuf::Descriptor* DimmerCommand_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  DimmerCommand_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_homeControl_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_homeControl_2eproto() {
  protobuf_AddDesc_homeControl_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "homeControl.proto");
  GOOGLE_CHECK(file != NULL);
  DimmerCommand_descriptor_ = file->message_type(0);
  static const int DimmerCommand_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DimmerCommand, channel_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DimmerCommand, level_),
  };
  DimmerCommand_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      DimmerCommand_descriptor_,
      DimmerCommand::default_instance_,
      DimmerCommand_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DimmerCommand, _has_bits_[0]),
      -1,
      -1,
      sizeof(DimmerCommand),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DimmerCommand, _internal_metadata_),
      -1);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_homeControl_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      DimmerCommand_descriptor_, &DimmerCommand::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_homeControl_2eproto() {
  delete DimmerCommand::default_instance_;
  delete DimmerCommand_reflection_;
}

void protobuf_AddDesc_homeControl_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AddDesc_homeControl_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\021homeControl.proto\022\013homeControl\"/\n\rDimm"
    "erCommand\022\017\n\007channel\030\001 \002(\005\022\r\n\005level\030\002 \002("
    "\005", 81);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "homeControl.proto", &protobuf_RegisterTypes);
  DimmerCommand::default_instance_ = new DimmerCommand();
  DimmerCommand::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_homeControl_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_homeControl_2eproto {
  StaticDescriptorInitializer_homeControl_2eproto() {
    protobuf_AddDesc_homeControl_2eproto();
  }
} static_descriptor_initializer_homeControl_2eproto_;

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int DimmerCommand::kChannelFieldNumber;
const int DimmerCommand::kLevelFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

DimmerCommand::DimmerCommand()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:homeControl.DimmerCommand)
}

void DimmerCommand::InitAsDefaultInstance() {
}

DimmerCommand::DimmerCommand(const DimmerCommand& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:homeControl.DimmerCommand)
}

void DimmerCommand::SharedCtor() {
  _cached_size_ = 0;
  channel_ = 0;
  level_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

DimmerCommand::~DimmerCommand() {
  // @@protoc_insertion_point(destructor:homeControl.DimmerCommand)
  SharedDtor();
}

void DimmerCommand::SharedDtor() {
  if (this != default_instance_) {
  }
}

void DimmerCommand::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* DimmerCommand::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return DimmerCommand_descriptor_;
}

const DimmerCommand& DimmerCommand::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_homeControl_2eproto();
  return *default_instance_;
}

DimmerCommand* DimmerCommand::default_instance_ = NULL;

DimmerCommand* DimmerCommand::New(::google::protobuf::Arena* arena) const {
  DimmerCommand* n = new DimmerCommand;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void DimmerCommand::Clear() {
// @@protoc_insertion_point(message_clear_start:homeControl.DimmerCommand)
#if defined(__clang__)
#define ZR_HELPER_(f) \
  _Pragma("clang diagnostic push") \
  _Pragma("clang diagnostic ignored \"-Winvalid-offsetof\"") \
  __builtin_offsetof(DimmerCommand, f) \
  _Pragma("clang diagnostic pop")
#else
#define ZR_HELPER_(f) reinterpret_cast<char*>(\
  &reinterpret_cast<DimmerCommand*>(16)->f)
#endif

#define ZR_(first, last) do {\
  ::memset(&first, 0,\
           ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
} while (0)

  ZR_(channel_, level_);

#undef ZR_HELPER_
#undef ZR_

  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  if (_internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->Clear();
  }
}

bool DimmerCommand::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:homeControl.DimmerCommand)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int32 channel = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &channel_)));
          set_has_channel();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_level;
        break;
      }

      // required int32 level = 2;
      case 2: {
        if (tag == 16) {
         parse_level:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &level_)));
          set_has_level();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:homeControl.DimmerCommand)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:homeControl.DimmerCommand)
  return false;
#undef DO_
}

void DimmerCommand::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:homeControl.DimmerCommand)
  // required int32 channel = 1;
  if (has_channel()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->channel(), output);
  }

  // required int32 level = 2;
  if (has_level()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->level(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:homeControl.DimmerCommand)
}

::google::protobuf::uint8* DimmerCommand::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:homeControl.DimmerCommand)
  // required int32 channel = 1;
  if (has_channel()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->channel(), target);
  }

  // required int32 level = 2;
  if (has_level()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->level(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:homeControl.DimmerCommand)
  return target;
}

int DimmerCommand::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:homeControl.DimmerCommand)
  int total_size = 0;

  if (has_channel()) {
    // required int32 channel = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->channel());
  }

  if (has_level()) {
    // required int32 level = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->level());
  }

  return total_size;
}
int DimmerCommand::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:homeControl.DimmerCommand)
  int total_size = 0;

  if (((_has_bits_[0] & 0x00000003) ^ 0x00000003) == 0) {  // All required fields are present.
    // required int32 channel = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->channel());

    // required int32 level = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->level());

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void DimmerCommand::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:homeControl.DimmerCommand)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const DimmerCommand* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const DimmerCommand>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:homeControl.DimmerCommand)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:homeControl.DimmerCommand)
    MergeFrom(*source);
  }
}

void DimmerCommand::MergeFrom(const DimmerCommand& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:homeControl.DimmerCommand)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_channel()) {
      set_channel(from.channel());
    }
    if (from.has_level()) {
      set_level(from.level());
    }
  }
  if (from._internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->MergeFrom(from.unknown_fields());
  }
}

void DimmerCommand::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:homeControl.DimmerCommand)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void DimmerCommand::CopyFrom(const DimmerCommand& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:homeControl.DimmerCommand)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DimmerCommand::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;

  return true;
}

void DimmerCommand::Swap(DimmerCommand* other) {
  if (other == this) return;
  InternalSwap(other);
}
void DimmerCommand::InternalSwap(DimmerCommand* other) {
  std::swap(channel_, other->channel_);
  std::swap(level_, other->level_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata DimmerCommand::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = DimmerCommand_descriptor_;
  metadata.reflection = DimmerCommand_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// DimmerCommand

// required int32 channel = 1;
bool DimmerCommand::has_channel() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void DimmerCommand::set_has_channel() {
  _has_bits_[0] |= 0x00000001u;
}
void DimmerCommand::clear_has_channel() {
  _has_bits_[0] &= ~0x00000001u;
}
void DimmerCommand::clear_channel() {
  channel_ = 0;
  clear_has_channel();
}
 ::google::protobuf::int32 DimmerCommand::channel() const {
  // @@protoc_insertion_point(field_get:homeControl.DimmerCommand.channel)
  return channel_;
}
 void DimmerCommand::set_channel(::google::protobuf::int32 value) {
  set_has_channel();
  channel_ = value;
  // @@protoc_insertion_point(field_set:homeControl.DimmerCommand.channel)
}

// required int32 level = 2;
bool DimmerCommand::has_level() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
void DimmerCommand::set_has_level() {
  _has_bits_[0] |= 0x00000002u;
}
void DimmerCommand::clear_has_level() {
  _has_bits_[0] &= ~0x00000002u;
}
void DimmerCommand::clear_level() {
  level_ = 0;
  clear_has_level();
}
 ::google::protobuf::int32 DimmerCommand::level() const {
  // @@protoc_insertion_point(field_get:homeControl.DimmerCommand.level)
  return level_;
}
 void DimmerCommand::set_level(::google::protobuf::int32 value) {
  set_has_level();
  level_ = value;
  // @@protoc_insertion_point(field_set:homeControl.DimmerCommand.level)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace homeControl

// @@protoc_insertion_point(global_scope)
