// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: homeControl.proto

#ifndef PROTOBUF_homeControl_2eproto__INCLUDED
#define PROTOBUF_homeControl_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace homeControl {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_homeControl_2eproto();
void protobuf_AssignDesc_homeControl_2eproto();
void protobuf_ShutdownFile_homeControl_2eproto();

class DimmerCommand;

// ===================================================================

class DimmerCommand : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:homeControl.DimmerCommand) */ {
 public:
  DimmerCommand();
  virtual ~DimmerCommand();

  DimmerCommand(const DimmerCommand& from);

  inline DimmerCommand& operator=(const DimmerCommand& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const DimmerCommand& default_instance();

  void Swap(DimmerCommand* other);

  // implements Message ----------------------------------------------

  inline DimmerCommand* New() const { return New(NULL); }

  DimmerCommand* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const DimmerCommand& from);
  void MergeFrom(const DimmerCommand& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(DimmerCommand* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 channel = 1;
  bool has_channel() const;
  void clear_channel();
  static const int kChannelFieldNumber = 1;
  ::google::protobuf::int32 channel() const;
  void set_channel(::google::protobuf::int32 value);

  // required int32 level = 2;
  bool has_level() const;
  void clear_level();
  static const int kLevelFieldNumber = 2;
  ::google::protobuf::int32 level() const;
  void set_level(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:homeControl.DimmerCommand)
 private:
  inline void set_has_channel();
  inline void clear_has_channel();
  inline void set_has_level();
  inline void clear_has_level();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 channel_;
  ::google::protobuf::int32 level_;
  friend void  protobuf_AddDesc_homeControl_2eproto();
  friend void protobuf_AssignDesc_homeControl_2eproto();
  friend void protobuf_ShutdownFile_homeControl_2eproto();

  void InitAsDefaultInstance();
  static DimmerCommand* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// DimmerCommand

// required int32 channel = 1;
inline bool DimmerCommand::has_channel() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void DimmerCommand::set_has_channel() {
  _has_bits_[0] |= 0x00000001u;
}
inline void DimmerCommand::clear_has_channel() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void DimmerCommand::clear_channel() {
  channel_ = 0;
  clear_has_channel();
}
inline ::google::protobuf::int32 DimmerCommand::channel() const {
  // @@protoc_insertion_point(field_get:homeControl.DimmerCommand.channel)
  return channel_;
}
inline void DimmerCommand::set_channel(::google::protobuf::int32 value) {
  set_has_channel();
  channel_ = value;
  // @@protoc_insertion_point(field_set:homeControl.DimmerCommand.channel)
}

// required int32 level = 2;
inline bool DimmerCommand::has_level() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void DimmerCommand::set_has_level() {
  _has_bits_[0] |= 0x00000002u;
}
inline void DimmerCommand::clear_has_level() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void DimmerCommand::clear_level() {
  level_ = 0;
  clear_has_level();
}
inline ::google::protobuf::int32 DimmerCommand::level() const {
  // @@protoc_insertion_point(field_get:homeControl.DimmerCommand.level)
  return level_;
}
inline void DimmerCommand::set_level(::google::protobuf::int32 value) {
  set_has_level();
  level_ = value;
  // @@protoc_insertion_point(field_set:homeControl.DimmerCommand.level)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace homeControl

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_homeControl_2eproto__INCLUDED
